<?php

namespace App;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;

class GetStringCommand extends Command
{
    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub

        $this
            ->setName('GetString')
            ->addArgument('string', InputArgument::REQUIRED, 'Your string')
            ->addOption(
                'iterations',
                null,
                InputOption::VALUE_REQUIRED,
                'How many times should the string be printed?',
                2
            )
        ;

    }

    public function execute(InputInterface $input, OutputInterface $output): int
    {
        for ($i = 0; $i < $input->getOption('iterations'); $i++) {
            $output->writeln($input->getArgument('string'));
        }

        return Command::SUCCESS;
    }
}
